{% set name = "btk" %}
{% set version = "0.4.dev0" %}
{% set sha256 = "b2fa608f9070811f9604c6835f83b4a0a8cd49976469c71d98a1d6f8391c18c0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Fork of the BTK project with python 3 support added on the latest commit from Dec 13, 2015 BTK was abandoned.
  url: https://github.com/melund/BTKCore/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 1
  skip: true  # [py < 36]


requirements:
  build:
    - cmake
    - jom  # [win]
    - ninja  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - swig
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - Testing/Python
  imports:
    - btk
  requires:
    - git  # [not win]
  

about:
  home: https://github.com/Biomechanical-ToolKit/BTKCore
  license: BSD-3-Clause
  license_family: BSD
  license_file: Copyright.txt
  summary: 'BTK is an open-source and cross-platform library for biomechanical analysis'
  description: |
    BTK is an open-source and cross-platform library for biomechanical analysis.
    BTK can read and write acquisition files and can modify them..
  doc_url: http://biomechanical-toolkit.github.io/
  dev_url: https://github.com/Biomechanical-ToolKit/BTKCore

extra:
  recipe-maintainers:
    - melund
